### ISSUE TITLE
Integration test failing with error : Unexpected exception in CPS VM thread

### ISSUE THREAD

**Issue by nehakanekar** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#100]
Just by adding this dependency **{"com.google.cloud", "google-cloud-storage", "1.105.0"}** in my gradle project , one of the integration tests which looks something like this : 

**---------------------------------------------------------------------**
void "buildInit library that uses declarative pipeline libraries"() {
        final CpsFlowDefinition flow = new CpsFlowDefinition('''
        def envDef = [:]
        executePipeline(envDef) {
            stage('Init') {
                //init
            }
        }
    '''.stripIndent(), true)
        final WorkflowJob workflowJob = rule.createProject(WorkflowJob, 'project')
        workflowJob.definition = flow
        final WorkflowRun run = rule.buildAndAssertSuccess(workflowJob)
        rule.assertLogContains('[WARN]:[executePipeline]: some msg', run)
    }
**---------------------------------------------------------------------**

 **is failing with the following error :** 

[Pipeline] End of Pipeline
java.lang.IllegalStateException: Outcome is already set
    at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.setOutcome(CpsBodyExecution.java:332)
    at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.access$900(CpsBodyExecution.java:65)
    at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:358)
    at com.cloudbees.groovy.cps.impl.ContinuationGroup.throwException(ContinuationGroup.java:157)
    at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:49)
    at com.cloudbees.groovy.cps.Next.step(Next.java:83)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
    at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
    at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
    at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
    at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:347)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:259)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:247)
    at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

hudson.UDPBroadcastThread#run: Cannot listen to UDP port 33,848, skipping: java.net.SocketException: Can't assign requested address
   0.827 [id=58]	WARNING	o.j.p.w.cps.CpsVmExecutorService#reportProblem: Unexpected exception in CPS VM thread: CpsFlowExecution[Owner[project/1:project #1]]
java.lang.IllegalStateException: Outcome is already set
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.setOutcome(CpsBodyExecution.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.access$900(CpsBodyExecution.java:65)

P.S. By running the command -> **./gradlew clean build** in my local machine, I am able to reproduce this issue.

**Comment by mkobit** [comment]
This is an old issue, and hard to say without a full reproducer repository. It is possible that the transitive dependencies from the dependency you added may screw up the Jenkins runtime.
