### ISSUE TITLE
Could not initialize class com.mkobit.jenkins.pipelines.CodegenTypesKt

### ISSUE THREAD

**Issue by gaborbernat** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#68]
When I try to build one of the example projects, e.g. ``jenkins-pipeline-shared-libraries-gradle-plugin/src/pipelineTestResources/projects/basic-WorkflowJob-usage``

```12:20:42.096 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin org.gradle.api.plugins.GroovyPlugin to root project 'basic-WorkflowJob-usage''                 
12:20:42.096 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin org.gradle.api.plugins.GroovyPlugin to root project 'basic-WorkflowJob-usage'' completed                  
12:20:42.096 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin com.mkobit.jenkins.pipelines.JenkinsIntegrationPlugin to root project 'basic-WorkflowJob-usage'' started
12:20:42.097 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin com.mkobit.jenkins.pipelines.JenkinsIntegrationPlugin to root project 'basic-WorkflowJob-usage''
12:20:42.097 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin com.mkobit.jenkins.pipelines.JenkinsIntegrationPlugin to root project 'basic-WorkflowJob-usage'' completed
12:20:42.097 [DEBUG] [com.mkobit.jenkins.pipelines.SharedLibraryPlugin] Adding repository named JenkinsPublic with URL https://repo.jenkins-ci.org/public/                       
12:20:42.098 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin com.mkobit.jenkins.pipelines.shared-library to root project 'basic-WorkflowJob-usage''
12:20:42.098 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin com.mkobit.jenkins.pipelines.shared-library to root project 'basic-WorkflowJob-usage'' completed
12:20:42.098 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply script build.gradle to root project 'basic-WorkflowJob-usage''
12:20:42.098 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply script build.gradle to root project 'basic-WorkflowJob-usage'' completed
12:20:42.099 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.036 secs                                                      
12:20:42.099 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure project :'                                                          
12:20:42.099 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure project :' completed                                           
12:20:42.099 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure build'                                          
12:20:42.099 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure build' completed                                                       
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                                                                                               
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.                                                                      
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                                                                                                                       
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:                                                                                                                            
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not initialize class com.mkobit.jenkins.pipelines.CodegenTypesKt                                                                        
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                                                                                                                  
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:                                                                                                      
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.                                                                            
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                                                                                                                     
12:20:42.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:                                                                                                   
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.NoClassDefFoundError: Could not initialize class com.mkobit.jenkins.pipelines.CodegenTypesKt      
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.mkobit.jenkins.pipelines.SharedLibraryPlugin$setupIntegrationTest$$inlined$invoke$lambda$1.invoke(SharedLibraryPlugin.kt:327)
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.mkobit.jenkins.pipelines.SharedLibraryPlugin$setupIntegrationTest$$inlined$invoke$lambda$1.invoke(SharedLibraryPlugin.kt:32)
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.kotlin.dsl.PolymorphicDomainObjectContainerDelegateProvider.provideDelegate(NamedDomainObjectContainerExtensions.kt:167)
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.mkobit.jenkins.pipelines.SharedLibraryPlugin.setupIntegrationTest(SharedLibraryPlugin.kt:324)  
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.mkobit.jenkins.pipelines.SharedLibraryPlugin.apply(SharedLibraryPlugin.kt:97)                            
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.mkobit.jenkins.pipelines.SharedLibraryPlugin.apply(SharedLibraryPlugin.kt:32)                            
12:20:42.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)   
```

**Comment by gaborbernat** [comment]
Seems this is an incompatibility with Java ``9+`` of the plugin.

**Comment by mkobit** [comment]
I haven't made much of an effort to support Java 9 yet (https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/issues/7) as Jenkins itself hasn't made much progress with Java 9 (https://issues.jenkins-ci.org/browse/JENKINS-40689). It might be that time to add better support though
