### ISSUE TITLE
compileTestKotlin FAILED

### ISSUE THREAD

**Issue by nedmark** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#99]
λ gradlew build

> Configure project :
Inferred project: jenkins-pipeline-shared-libraries-gradle-plugin, version: 0.11.0-dev.0+cd5f95c

> Task :compileTestKotlin
The `kotlin-dsl` plugin applied to root project 'jenkins-pipeline-shared-libraries-gradle-plugin' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/5.5.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: D:\Git\InteliJ_Jenkins_Pipeline_plugIn\jenkins-pipeline-shared-libraries-gradle-plugin\build\classes\kotlin\test\com\mkobit\jenkins\pipelines\IntegrationTestSourceIntegrationTest$"check" lifecycle task executes "integrationTest"$1.class (The filename, directory name, or volume label syntax is incorrect)
File being compiled at position: file://D:/Git/InteliJ_Jenkins_Pipeline_plugIn/jenkins-pipeline-shared-libraries-gradle-plugin/src/test/kotlin/com/mkobit/jenkins/pipelines/IntegrationTestSourceIntegrationTest.kt
The root cause was thrown at: FileOutputStream.java:-2
        at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:75)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:99)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:70)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:455)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:154)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:131)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execAndOutputXml(CLICompiler.kt:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileInProcessImpl(GradleKotlinCompilerWork.kt:351)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.access$compileInProcessImpl(GradleKotlinCompilerWork.kt:66)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:319)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:66)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: D:\Git\InteliJ_Jenkins_Pipeline_plugIn\jenkins-pipeline-shared-libraries-gradle-plugin\build\classes\kotlin\test\com\mkobit\jenkins\pipelines\IntegrationTestSourceIntegrationTest$"check" lifecycle task executes "integrationTest"$1.class (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1274)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1268)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1253)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:32)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:37)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:41)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.writeOutput(KotlinToJVMBytecodeCompiler.kt:90)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.access$writeOutput(KotlinToJVMBytecodeCompiler.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:70)
        at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:335)
        at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:334)
        at org.jetbrains.kotlin.codegen.state.GenerationState.afterIndependentPart(GenerationState.kt:291)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:68)
        ... 25 more

e: Compiler terminated with internal error

> Task :compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
12 actionable tasks: 1 executed, 11 up-to-date

D:\Git\InteliJ_Jenkins_Pipeline_plugIn\jenkins-pipeline-shared-libraries-gradle-plugin (master -> origin)

**Comment by nedmark** [comment]
This Kotlin compile error is coming.
Regards.

**Comment by nedmark** [comment]
Here is the output from debug:
17:40:08.479 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :compileTestKotlin FAILED
17:40:22.689 [DEBUG] [org.gradle.api.Task] Finished executing kotlin compiler using in-process strategy
17:40:22.689 [WARN] [org.gradle.api.Task] The `kotlin-dsl` plugin applied to root project 'jenkins-pipeline-shared-libraries-gradle-plugin' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/5.5.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
17:40:22.689 [DEBUG] [org.gradle.api.Task] v: Using Kotlin home directory <no_path>
17:40:22.689 [DEBUG] [org.gradle.api.Task] v: Configuring the compilation environment
17:40:22.690 [ERROR] [org.gradle.api.Task] e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: D:\Git\InteliJ_Jenkins_Pipeline_plugIn\jenkins-pipeline-shared-libraries-gradle-plugin\build\classes\kotlin\test\com\mkobit\jenkins\pipelines\IntegrationTestSourceIntegrationTest$"check" lifecycle task executes "integrationTest"$1.class (The filename, directory name, or volume label syntax is incorrect)
File being compiled at position: file://D:/Git/InteliJ_Jenkins_Pipeline_plugIn/jenkins-pipeline-shared-libraries-gradle-plugin/src/test/kotlin/com/mkobit/jenkins/pipelines/IntegrationTestSourceIntegrationTest.kt
The root cause was thrown at: FileOutputStream.java:-2
        at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:75)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:99)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:70)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:455)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:154)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:131)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execAndOutputXml(CLICompiler.kt:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileInProcessImpl(GradleKotlinCompilerWork.kt:351)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.access$compileInProcessImpl(GradleKotlinCompilerWork.kt:66)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:319)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork$compileInProcess$future$1.call(GradleKotlinCompilerWork.kt:66)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: D:\Git\InteliJ_Jenkins_Pipeline_plugIn\jenkins-pipeline-shared-libraries-gradle-plugin\build\classes\kotlin\test\com\mkobit\jenkins\pipelines\IntegrationTestSourceIntegrationTest$"check" lifecycle task executes "integrationTest"$1.class (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1274)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1268)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1253)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:32)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:37)
        at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:41)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.writeOutput(KotlinToJVMBytecodeCompiler.kt:90)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.access$writeOutput(KotlinToJVMBytecodeCompiler.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:70)
        at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:335)
        at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:334)
        at org.jetbrains.kotlin.codegen.state.GenerationState.afterIndependentPart(GenerationState.kt:291)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:68)
        ... 25 more

17:40:22.691 [ERROR] [org.gradle.api.Task] e: Compiler terminated with internal error
17:40:22.693 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute execute for :compileTestKotlin'
17:40:22.694 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute execute for :compileTestKotlin' completed
17:40:22.694 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter] Fingerprinting property destinationDir (Output) for task ':compileTestKotlin'
17:40:22.732 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for {} from context.

**Comment by mkobit** [comment]
Sorry, this issue is old and no reproducer was attached. Closing.
